from __future__ import annotations

from pathlib import Path


def replace_once(path: Path, old: str, new: str, label: str) -> None:
    text = path.read_text(encoding="utf-8")
    count = text.count(old)
    if count != 1:
        raise SystemExit(f"{label}: expected one marker, found {count}")
    path.write_text(text.replace(old, new, 1), encoding="utf-8")


def replace_in_function(
    path: Path,
    function_name: str,
    old: str,
    new: str,
    label: str,
) -> None:
    text = path.read_text(encoding="utf-8")
    marker = f"def {function_name}("
    start = text.index(marker)
    next_start = text.find("\ndef ", start + len(marker))
    if next_start == -1:
        next_start = len(text)
    block = text[start:next_start]
    count = block.count(old)
    if count != 1:
        raise SystemExit(f"{label}: expected one marker, found {count}")
    block = block.replace(old, new, 1)
    path.write_text(text[:start] + block + text[next_start:], encoding="utf-8")


binary_sensor = Path("custom_components/smartthings_web/binary_sensor.py")
replace_once(
    binary_sensor,
    '            object_id_name="presence" if state.attribute == "presence" else None,\n',
    '            object_id_name=(\n'
    '                "presence"\n'
    '                if state.attribute == "presence"\n'
    '                and sum(\n'
    '                    candidate.attribute == "presence"\n'
    '                    for candidate in device.states.values()\n'
    '                )\n'
    '                == 1\n'
    '                else None\n'
    '            ),\n',
    "single-presence entity object ID",
)


integration = Path("custom_components/smartthings_web/__init__.py")
single_presence_case = (
    '        if (\n'
    '            domain_value == "binary_sensor"\n'
    '            and getattr(state, "attribute", None) == "presence"\n'
    '            and _single_presence_state(device, state)\n'
    '        ):\n'
    '            return canonical_entity_object_id(inventory, device, "presence")\n'
)
replace_in_function(
    integration,
    "_canonical_registry_suggested_object_id",
    '    if state is not None:\n'
    '        if _registry_state_is_primary_control(domain_value, device, state):\n',
    '    if state is not None:\n'
    + single_presence_case
    + '        if _registry_state_is_primary_control(domain_value, device, state):\n',
    "single-presence suggested object ID metadata",
)
replace_in_function(
    integration,
    "_canonical_registry_object_id_base",
    '    if state is not None:\n'
    '        if _registry_state_is_primary_control(domain_value, device, state):\n',
    '    if state is not None:\n'
    '        if (\n'
    '            domain_value == "binary_sensor"\n'
    '            and getattr(state, "attribute", None) == "presence"\n'
    '            and _single_presence_state(device, state)\n'
    '        ):\n'
    '            return "presence"\n'
    '        if _registry_state_is_primary_control(domain_value, device, state):\n',
    "single-presence object ID base metadata",
)
replace_in_function(
    integration,
    "_canonical_generated_state_entity_id",
    '        and getattr(state, "attribute", None) == "presence"\n'
    '        and _generated_presence_state_entity_id(entity_entry, device, inventory)\n',
    '        and getattr(state, "attribute", None) == "presence"\n'
    '        and _single_presence_state(device, state)\n'
    '        and _generated_presence_state_entity_id(entity_entry, device, inventory)\n',
    "single-presence generated entity migration",
)
replace_once(
    integration,
    'def _generated_presence_state_entity_id(\n'
    '    entity_entry: object,\n'
    '    device: object,\n'
    '    inventory: BridgeInventory,\n'
    ') -> bool:\n'
    '    """Return whether a localized presence ID was generated by this integration."""\n',
    'def _single_presence_state(device: object, state: object) -> bool:\n'
    '    """Return whether this is the device\'s only presence channel."""\n'
    '    return (\n'
    '        getattr(state, "attribute", None) == "presence"\n'
    '        and sum(\n'
    '            getattr(candidate, "attribute", None) == "presence"\n'
    '            for candidate in getattr(device, "states", {}).values()\n'
    '        )\n'
    '        == 1\n'
    '    )\n'
    '\n'
    '\n'
    'def _generated_presence_state_entity_id(\n'
    '    entity_entry: object,\n'
    '    device: object,\n'
    '    inventory: BridgeInventory,\n'
    ') -> bool:\n'
    '    """Return whether a localized presence ID was generated by this integration."""\n'
    '    state = next(\n'
    '        (\n'
    '            candidate\n'
    '            for candidate in getattr(device, "states", {}).values()\n'
    '            if entity_unique_id(getattr(device, "device_id", ""), candidate)\n'
    '            == getattr(entity_entry, "unique_id", "")\n'
    '        ),\n'
    '        None,\n'
    '    )\n'
    '    if state is None or not _single_presence_state(device, state):\n'
    '        return False\n',
    "single-presence helper and guard",
)
replace_in_function(
    integration,
    "_generated_primary_switch_entity_id",
    '    for metadata_name in (\n'
    '        getattr(entity_entry, "original_name", None),\n'
    '        getattr(entity_entry, "object_id_base", None),\n'
    '        getattr(entity_entry, "suggested_object_id", None),\n'
    '    ):\n'
    '        if not isinstance(metadata_name, str) or not metadata_name.strip():\n'
    '            continue\n'
    '        metadata_slug = slugify(metadata_name) or None\n'
    '        if not metadata_slug:\n'
    '            continue\n'
    '        generated.add(metadata_slug)\n'
    '        if not metadata_slug.startswith(f"{object_id}_"):\n'
    '            generated.add(f"{object_id}_{metadata_slug}")\n',
    '    for metadata_name in (\n'
    '        getattr(entity_entry, "original_name", None),\n'
    '        getattr(entity_entry, "object_id_base", None),\n'
    '    ):\n'
    '        if not isinstance(metadata_name, str) or not metadata_name.strip():\n'
    '            continue\n'
    '        metadata_slug = slugify(metadata_name) or None\n'
    '        if not metadata_slug or metadata_slug == object_id:\n'
    '            continue\n'
    '        generated.add(f"{object_id}_{metadata_slug}")\n',
    "primary switch generated suffix detection",
)


models = Path("custom_components/smartthings_web/models.py")
replace_in_function(
    models,
    "switch_name_overrides",
    '        if label is None and is_primary:\n'
    '            label = "전원"\n',
    '        if (\n'
    '            label is None\n'
    '            and is_primary\n'
    '            and control is not None\n'
    '            and control.transport != "advanced"\n'
    '            and isinstance(control.label, str)\n'
    '            and bool(control.label.strip())\n'
    '            and _web_control_label(control.label) is None\n'
    '        ):\n'
    '            label = _readable_state_token(\n'
    '                state.component_role or state.component, "component"\n'
    '            )\n'
    '        if label is None and is_primary:\n'
    '            label = "전원"\n',
    "unsafe Web switch label structural fallback",
)


window_test = Path(
    "custom_components/smartthings_web/tests/test_window_sensor_platform_entities.py"
)
replace_once(
    window_test,
    '        state: object,\n'
    '        name: str | None,\n'
    '    ) -> None:\n',
    '        state: object,\n'
    '        name: str | None,\n'
    '        **_kwargs: object,\n'
    '    ) -> None:\n',
    "window platform entity stub keyword compatibility",
)
