"""Constants for SmartThings Web."""

DOMAIN = "smartthings_web"
CONF_BRIDGE_URL = "bridge_url"
CONF_BRIDGE_TOKEN = "bridge_token"
CONF_CONTROL_MODE = "control_mode"
CONF_LOCATION_ID = "location_id"
CONTROL_MODE_READ_ONLY = "read_only"
CONTROL_MODE_SAFE_CONTROL = "safe_control"
DEFAULT_BRIDGE_URL = "http://local-smartthings-web-bridge:8100"
REPAIR_SAMSUNG_LOGIN_REQUIRED = "samsung_login_required"
